# Generated by Django 5.2 on 2025-05-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transakcja',
            old_name='uzytkownik',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transakcja',
            name='tytul',
        ),
        migrations.AddField(
            model_name='transakcja',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kategoria',
            name='nazwa',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transakcja',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transakcja',
            name='typ',
            field=models.CharField(choices=[('przychód', 'Przychód'), ('wydatek', 'Wydatek')], max_length=10),
        ),
    ]
