# Generated by Django 5.2 on 2025-05-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanse', '0002_rename_uzytkownik_transakcja_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='budzet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
